# Generated by Django 5.2.8 on 2025-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discount_tax_item_currency_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5),
        ),
    ]
