# Generated by Django 5.2.8 on 2025-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_tax_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='ID купона в Stripe', max_length=255),
        ),
    ]
