# Generated by Django 5.2.8 on 2025-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_discount_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Stripe Tax Rate ID', max_length=255),
        ),
    ]
