# Generated by Django 5.2.8 on 2025-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_tax_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_id_eur',
            field=models.CharField(blank=True, help_text='ID купона в Stripe EUR', max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_id_usd',
            field=models.CharField(blank=True, help_text='ID купона в Stripe USD', max_length=255),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id_eur',
            field=models.CharField(blank=True, help_text='Stripe Tax Rate ID EUR', max_length=255),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id_usd',
            field=models.CharField(blank=True, help_text='Stripe Tax Rate ID USD', max_length=255),
        ),
    ]
