# Generated by Django 5.2.8 on 2025-11-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_discount_stripe_id_remove_tax_stripe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Discount percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Tax percentage', max_digits=5),
        ),
    ]
